from selenium.webdriver.common.by import By
from pages.base_page import BasePage
from selenium.webdriver.support.ui import Select

class RegistrationPage(BasePage):
    SIGNUP_LOGIN_BUTTON = (By.XPATH, "//a[contains(text(), ' Signup / Login')]")
    NEW_USER_SIGNUP_TEXT = (By.XPATH, "//h2[contains(text(),'New User Signup!')]")
    NAME_INPUT = (By.NAME, "name")
    EMAIL_INPUT = (By.XPATH, "//input[@data-qa='signup-email']")
    SIGNUP_BUTTON = (By.XPATH, "//button[@data-qa='signup-button']")
    ACCOUNT_INFO_TEXT = (By.XPATH, "//b[text()='Enter Account Information']")
    PASSWORD_INPUT = (By.XPATH, "//input[@id='password']")
    NEWSLETTER_CHECKBOX = (By.XPATH, "//input[@id='newsletter']")
    OFFERS_CHECKBOX = (By.XPATH, "//input[@id='optin']")
    FIRST_NAME_INPUT = (By.XPATH, "//input[@id='first_name']")
    LAST_NAME_INPUT = (By.XPATH, "//input[@id='last_name']")
    COMPANY_INPUT = (By.XPATH, "//input[@id='company']")
    ADDRESS1_INPUT = (By.XPATH, "//input[@id='address1']")
    ADDRESS2_INPUT = (By.XPATH, "//input[@id='address2']")
    COUNTRY_DROPDOWN = (By.XPATH, "//*[@id='country']")
    STATE_INPUT = (By.XPATH, "//input[@id='state']")
    CITY_INPUT = (By.XPATH, "//input[@id='city']")
    ZIPCODE_INPUT = (By.XPATH, "//input[@id='zipcode']")
    MOBILE_NUMBER_INPUT = (By.XPATH, "//input[@id='mobile_number']")
    CREATE_ACCOUNT_BUTTON = (By.XPATH, "//button[text()='Create Account']")
    ACCOUNT_CREATED_TEXT = (By.XPATH, "//b[text()='Account Created!']")
    CONTINUE_BUTTON = (By.XPATH, "//a[text()='Continue']")
    LOGGED_IN_TEXT = (By.XPATH, "//a[text()=' Logged in as ']")
   # DELETE_ACCOUNT_BUTTON = (By.XPATH, "//a[text()=' Delete Account']")
   # ACCOUNT_DELETED_TEXT = (By.XPATH, "//b[text()='Account Deleted!']")

    def register_user(self, user_details):
        self.click_element(self.SIGNUP_LOGIN_BUTTON)
        assert self.is_visible(self.NEW_USER_SIGNUP_TEXT)
        self.enter_text(self.NAME_INPUT, user_details["name"])
        self.enter_text(self.EMAIL_INPUT, user_details["email"])
        self.click_element(self.SIGNUP_BUTTON)
        assert self.is_visible(self.ACCOUNT_INFO_TEXT)
        self.enter_text(self.PASSWORD_INPUT, user_details["password"])
        self.driver.find_element(*self.NEWSLETTER_CHECKBOX).click()
        self.driver.find_element(*self.OFFERS_CHECKBOX).click()
        self.enter_text(self.FIRST_NAME_INPUT, user_details["first_name"])
        self.enter_text(self.LAST_NAME_INPUT, user_details["last_name"])
        self.enter_text(self.COMPANY_INPUT, user_details["company"])
        self.enter_text(self.ADDRESS1_INPUT, user_details["address1"])
        self.enter_text(self.ADDRESS2_INPUT, user_details["address2"])
        Select(self.driver.find_element(*self.COUNTRY_DROPDOWN)).select_by_visible_text(user_details["country"])
        self.enter_text(self.STATE_INPUT, user_details["state"])
        self.enter_text(self.CITY_INPUT, user_details["city"])
        self.enter_text(self.ZIPCODE_INPUT, user_details["zipcode"])
        self.enter_text(self.MOBILE_NUMBER_INPUT, user_details["mobile_number"])
        self.click_element(self.CREATE_ACCOUNT_BUTTON)
        assert self.is_visible(self.ACCOUNT_CREATED_TEXT)
        self.click_element(self.CONTINUE_BUTTON)
        assert self.is_visible(self.LOGGED_IN_TEXT)
       # self.click_element(self.DELETE_ACCOUNT_BUTTON)
        #assert self.is_visible(self.ACCOUNT_DELETED_TEXT)
       # self.click_element(self.CONTINUE_BUTTON)